#include "arduino_secrets.h"


/* 
  Sketch generated by the Arduino IoT Cloud Thing "Beer"
  https://create.arduino.cc/cloud/things/7da751ca-bad4-4124-962c-cc0886c157f7 

  Arduino IoT Cloud Properties description

  The following variables are automatically generated and updated when changes are made to the Thing properties

  CloudDimmedLight beer;

  Properties which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <Servo.h>

int LED = 5;
//int buttonInput = 3;
//int lightOutput = 13;
//int buttonState = 0;
int servoPin = 7;
Servo Servo1;
int pos = 0;

void setup() {
  // Initialize serial and wait for port to open:
  pinMode(LED, OUTPUT);
  Servo1.attach(servoPin);
    Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  //digitalWrite(LED, HIGH);

  ArduinoCloud.update();
  
}


void onBeerChange() {
 
 Serial.println("Im here");
 if(beer.getSwitch()){
   Serial.println("Changing to high");
   digitalWrite(LED, HIGH);
   for(pos = 0; pos <=180; pos+=5){
    Servo1.write(pos);
    delay(20);
   }
   for(pos = 180; pos >=0; pos -=5){
    Servo1.write(pos);
    delay(20);
   }
   
   digitalWrite(LED, LOW);
 }

  
  
}
